import { brand, destructive, info, neutral, success, viz, warning } from './colors.js';
import { radii } from './radii.js';

export const lightTheme = {
  background: 'oklch(0.96 0.004 231)',
  foreground: neutral[950],
  // Surface ramp. Light mode holds an even near-white ramp (canvas 0.96 to
  // surface 0.98 to pure white) so nested tiers stay distinct: a light-gray
  // canvas, an off-white content pane, and white raised cards. Overlays are
  // white too and separate by shadow, not lightness.
  surface: 'oklch(0.98 0.004 231)',
  'surface-raised': 'oklch(1 0 0)',
  overlay: 'oklch(1 0 0)',
  inset: 'color-mix(in oklab, black 5%, transparent)',
  card: 'var(--surface-raised)', // raised tier: lifts cards off a --surface content pane
  'card-foreground': neutral[950],
  popover: 'var(--overlay)',
  'popover-foreground': neutral[950],
  primary: neutral[900],
  'primary-foreground': neutral[50],
  brand: brand[500],
  'brand-foreground': neutral[950],
  // Intensity slots are foreground mixes so they hold on any ramp tier; the
  // percentages reproduce the previous absolute values on the default surface.
  secondary: 'color-mix(in oklab, var(--foreground) 7%, transparent)',
  'secondary-foreground': neutral[900],
  muted: 'color-mix(in oklab, var(--foreground) 5%, transparent)',
  'muted-foreground': neutral[600],
  accent: 'color-mix(in oklab, var(--foreground) 8%, transparent)',
  'accent-foreground': neutral[900],
  destructive: destructive[600],
  'destructive-foreground': 'oklch(0.98 0.01 25)',
  'destructive-subtle': destructive[100],
  'destructive-subtle-foreground': destructive[900],
  'destructive-border': destructive[200],
  success: success[600],
  'success-foreground': 'oklch(0.98 0.01 145)',
  'success-subtle': success[100],
  'success-subtle-foreground': success[900],
  'success-border': success[200],
  warning: warning[500],
  'warning-foreground': warning[950],
  'warning-subtle': warning[100],
  'warning-subtle-foreground': warning[900],
  'warning-border': warning[200],
  info: info[600],
  'info-foreground': 'oklch(0.98 0.01 250)',
  'info-subtle': info[100],
  'info-subtle-foreground': info[900],
  'info-border': info[200],
  'neutral-subtle': neutral[100],
  'neutral-subtle-foreground': neutral[900],
  'neutral-border': neutral[200],
  // Code annotation slots (Shiki notation: line/word highlight, diff add/remove).
  // Backgrounds are 10% alpha mixes so they read on any surface tier and keep
  // the syntax-highlighted text legible; accents draw the solid gutter bar.
  'code-highlight': `color-mix(in oklab, ${info[500]} 10%, transparent)`,
  'code-highlight-accent': info[500],
  'code-diff-add': `color-mix(in oklab, ${success[500]} 10%, transparent)`,
  'code-diff-add-accent': success[500],
  'code-diff-remove': `color-mix(in oklab, ${destructive[500]} 10%, transparent)`,
  'code-diff-remove-accent': destructive[500],
  border: 'oklch(0.86 0.004 231)',
  input: 'oklch(0.86 0.004 231)',
  ring: neutral[400],
  radius: radii.md,
  'chart-1': viz[1],
  'chart-2': viz[2],
  'chart-3': viz[3],
  'chart-4': viz[4],
  'chart-5': viz[5],
  sidebar: 'var(--background)',
  'sidebar-foreground': 'oklch(0.3 0.007 231)',
  'sidebar-primary': neutral[900],
  'sidebar-primary-foreground': neutral[50],
  'sidebar-accent': 'oklch(0.935 0.004 231)',
  'sidebar-accent-foreground': neutral[900],
  'sidebar-border': 'oklch(0.86 0.004 231)',
  'sidebar-ring': neutral[400],
} as const;

export const darkTheme = {
  background: neutral[950],
  foreground: 'oklch(0.92 0.004 231)',
  // Dark mode expresses all four tiers through lightness. Persistent surfaces
  // stay close to the canvas so large panes and cards retain a deep appearance;
  // temporary overlays take the brightest step to remain clearly distinct.
  surface: 'oklch(0.16 0.007 231)',
  'surface-raised': 'oklch(0.18 0.007 231)',
  overlay: 'oklch(0.2 0.007 231)',
  inset: 'color-mix(in oklab, black 40%, transparent)',
  card: 'var(--surface-raised)', // raised tier: lifts cards off a --surface content pane
  'card-foreground': 'oklch(0.92 0.004 231)',
  popover: 'var(--overlay)',
  'popover-foreground': 'oklch(0.95 0.004 231)',
  primary: neutral[100],
  'primary-foreground': neutral[900],
  brand: brand[500],
  'brand-foreground': neutral[950],
  secondary: 'color-mix(in oklab, var(--foreground) 7%, transparent)',
  'secondary-foreground': 'oklch(0.95 0.004 231)',
  muted: 'color-mix(in oklab, var(--foreground) 4%, transparent)',
  'muted-foreground': 'oklch(0.65 0.005 231)',
  accent: 'color-mix(in oklab, var(--foreground) 9%, transparent)',
  'accent-foreground': 'oklch(0.95 0.004 231)',
  // One step lighter than light mode (600 → 500): the mid-dark red reads as
  // muddy on a near-black canvas, so lift it up the ramp to hold its weight.
  destructive: destructive[500],
  'destructive-foreground': 'oklch(0.98 0.01 25)',
  // Subtle backgrounds are 40% alpha so they sit on any surface tier instead
  // of only matching the canvas.
  'destructive-subtle': `color-mix(in oklab, ${destructive[900]} 40%, transparent)`,
  'destructive-subtle-foreground': destructive[300],
  'destructive-border': destructive[800],
  success: success[600],
  'success-foreground': 'oklch(0.98 0.01 145)',
  'success-subtle': `color-mix(in oklab, ${success[900]} 40%, transparent)`,
  'success-subtle-foreground': success[300],
  'success-border': success[800],
  warning: warning[500],
  'warning-foreground': warning[950],
  'warning-subtle': `color-mix(in oklab, ${warning[900]} 40%, transparent)`,
  'warning-subtle-foreground': warning[300],
  'warning-border': warning[800],
  info: info[600],
  'info-foreground': 'oklch(0.98 0.01 250)',
  'info-subtle': `color-mix(in oklab, ${info[900]} 40%, transparent)`,
  'info-subtle-foreground': info[300],
  'info-border': info[800],
  'neutral-subtle': `color-mix(in oklab, ${neutral[900]} 40%, transparent)`,
  'neutral-subtle-foreground': neutral[300],
  'neutral-border': neutral[800],
  // Same 10% alpha recipe as light mode: the 500-step hues carry enough chroma
  // to read as tint on the dark surface ramp without drowning the token colors.
  'code-highlight': `color-mix(in oklab, ${info[500]} 10%, transparent)`,
  'code-highlight-accent': info[500],
  'code-diff-add': `color-mix(in oklab, ${success[500]} 10%, transparent)`,
  'code-diff-add-accent': success[500],
  'code-diff-remove': `color-mix(in oklab, ${destructive[500]} 10%, transparent)`,
  'code-diff-remove-accent': destructive[500],
  // Foreground mixes like the intensity slots — neutral-800 tuned for the
  // canvas disappears on raised/overlay tiers. 17% renders ~neutral-800
  // on the canvas and degrades correctly above it.
  border: 'color-mix(in oklab, var(--foreground) 17%, transparent)',
  input: 'color-mix(in oklab, var(--foreground) 17%, transparent)',
  ring: neutral[500],
  'chart-1': viz[1],
  'chart-2': viz[2],
  'chart-3': viz[3],
  'chart-4': viz[4],
  'chart-5': viz[5],
  sidebar: 'var(--background)',
  'sidebar-foreground': 'oklch(0.85 0.004 231)',
  'sidebar-primary': neutral[100],
  'sidebar-primary-foreground': neutral[900],
  'sidebar-accent': 'oklch(0.18 0.007 231)',
  'sidebar-accent-foreground': 'oklch(0.95 0.004 231)',
  'sidebar-border': neutral[800],
  'sidebar-ring': neutral[500],
} as const;
