import { tokenGuidance } from '../packages/design-tokens/guidance/catalog.ts';
import { uiGuidance } from '../packages/ui/guidance/catalog.ts';
import { illustrationGuidance } from '../packages/ui/guidance/illustrations.ts';
import { screenRecipes } from '../packages/ui/guidance/recipes.ts';

const root = new URL('../', import.meta.url);
const checkOnly = Bun.argv.includes('--check');
const generatedHeader =
  '<!-- Generated by bun run skills:generate. Edit the guidance source, not this file. -->';

function sectionTitle(title: string) {
  return `## ${title}`;
}

function renderComponentDecisions() {
  const entries = uiGuidance.map((entry) => {
    const choices = entry.choices?.length
      ? [
          '',
          '**Choose:**',
          '',
          ...entry.choices.map((choice) => `- \`${choice.choice}\`: ${choice.when}`),
        ]
      : [];
    const related = entry.related?.length
      ? ['', `Related decisions: ${entry.related.map((id) => `\`${id}\``).join(', ')}.`]
      : [];

    return [
      sectionTitle(entry.title),
      '',
      entry.summary,
      '',
      ...entry.rules.map((rule) => `- **${rule.title}:** ${rule.body}`),
      ...choices,
      ...related,
    ].join('\n');
  });

  return [
    generatedHeader,
    '# Vendure UI component decisions',
    '',
    'Use these rules to select and compose components. Inspect the installed package source and types for exact APIs.',
    '',
    ...entries,
    '',
  ].join('\n');
}

function renderScreenRecipes() {
  const entries = screenRecipes.map((recipe) =>
    [
      sectionTitle(recipe.title),
      '',
      recipe.purpose,
      '',
      '**Invariants:**',
      '',
      ...recipe.invariants.map((invariant) => `- ${invariant}`),
      '',
      '### Dashboard extension skeleton',
      '',
      '```tsx',
      recipe.dashboardSkeleton,
      '```',
      '',
      '### Standalone consumer skeleton',
      '',
      '```tsx',
      recipe.standaloneSkeleton,
      '```',
    ].join('\n'),
  );

  return [
    generatedHeader,
    '# Vendure screen recipes',
    '',
    'Treat these as strong defaults. Begin from the closest recipe and preserve its hierarchy, action placement, responsive anatomy, and state handling. Deviate only for a concrete product requirement and report the reason.',
    '',
    ...entries,
    '',
  ].join('\n');
}

function renderIllustrations() {
  return [
    generatedHeader,
    '# Illustration selection',
    '',
    'Use one scenario-matched illustration for a whole empty or error region. Never repeat illustrations in table rows, list items, or cards inside an otherwise populated view; use an icon-chip fallback or no media there.',
    '',
    ...illustrationGuidance.map((item) => `- **${item.component}:** ${item.use}`),
    '',
  ].join('\n');
}

function renderTokenDecisions() {
  const entries = tokenGuidance.map((entry) =>
    [
      sectionTitle(entry.title),
      '',
      entry.summary,
      '',
      ...entry.rules.map((rule) => `- **${rule.title}:** ${rule.body}`),
    ].join('\n'),
  );

  return [
    generatedHeader,
    '# Vendure token decisions',
    '',
    'Apply these decisions to theme setup, styling, implementation, and review. Actual values remain authoritative in the installed design-tokens package.',
    '',
    ...entries,
    '',
  ].join('\n');
}

const outputs = new Map<string, string>([
  ['skills/vendure-ui/references/component-decisions.md', renderComponentDecisions()],
  ['skills/vendure-ui/references/screen-recipes.md', renderScreenRecipes()],
  ['skills/vendure-ui/references/illustrations.md', renderIllustrations()],
  ['skills/vendure-tokens/references/token-decisions.md', renderTokenDecisions()],
]);

function validateCatalog() {
  const ids = uiGuidance.map((entry) => entry.id);
  const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (duplicateIds.length > 0) {
    throw new Error(`Duplicate UI guidance ids: ${duplicateIds.join(', ')}`);
  }

  const storyDirectory = new URL('packages/ui/stories/', root);
  const coveredStories = new Set(uiGuidance.map((entry) => entry.sourceStory));
  const guidanceStories = Array.from(
    new Bun.Glob('*-guidance.stories.tsx').scanSync({ cwd: storyDirectory.pathname }),
  ).filter((story) => story !== 'token-guidance.stories.tsx');

  const missingCatalogEntries = guidanceStories.filter((story) => !coveredStories.has(story));
  const missingStoryFiles = Array.from(coveredStories).filter(
    (story) => !guidanceStories.includes(story),
  );

  if (missingCatalogEntries.length > 0 || missingStoryFiles.length > 0) {
    throw new Error(
      [
        missingCatalogEntries.length
          ? `Guidance stories missing catalog entries: ${missingCatalogEntries.join(', ')}`
          : '',
        missingStoryFiles.length
          ? `Catalog entries missing guidance stories: ${missingStoryFiles.join(', ')}`
          : '',
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }
}

validateCatalog();

const stale: string[] = [];
for (const [path, content] of outputs) {
  const file = Bun.file(new URL(path, root));
  const current = (await file.exists()) ? await file.text() : '';
  if (current === content) {
    continue;
  }
  if (checkOnly) {
    stale.push(path);
    continue;
  }
  await Bun.write(file, content);
}

if (stale.length > 0) {
  console.error(
    `Generated skill references are stale:\n${stale.map((path) => `- ${path}`).join('\n')}`,
  );
  console.error('Run `bun run skills:generate` and commit the results.');
  process.exit(1);
}

console.log(checkOnly ? 'Skill references are fresh.' : 'Generated skill references.');
